static const char gladestring [] = 
{
  "<?xml version=\"1.0\" ?><!-- Generated with glade 3.19.0 --><int"
  "erface><requires lib=\"gtk+\" version=\"3.8\"/><object class=\"G"
  "tkWindow\" id=\"window\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\""
  "title\" translatable=\"yes\">LightSearch</property><property nam"
  "e=\"modal\">True</property><property name=\"window_position\">ce"
  "nter</property><property name=\"default_width\">500</property><p"
  "roperty name=\"default_height\">100</property><property name=\"t"
  "ype_hint\">dialog</property><property name=\"skip_taskbar_hint\""
  ">True</property><property name=\"skip_pager_hint\">True</propert"
  "y><property name=\"decorated\">False</property><property name=\""
  "gravity\">center</property><child><object class=\"GtkOverlay\" i"
  "d=\"overlay1\"><property name=\"width_request\">500</property><p"
  "roperty name=\"height_request\">100</property><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</prop"
  "erty><child><object class=\"GtkImage\" id=\"image1\"><property n"
  "ame=\"width_request\">500</property><property name=\"height_requ"
  "est\">100</property><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"hali"
  "gn\">center</property><property name=\"valign\">center</property"
  "><property name=\"pixbuf\">internet.jpg</property></object><pack"
  "ing><property name=\"index\">1</property></packing></child><chil"
  "d type=\"overlay\"><object class=\"GtkBox\" id=\"box1\"><propert"
  "y name=\"name\">30</property><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property na"
  "me=\"margin_left\">30</property><property name=\"margin_right\">"
  "30</property><property name=\"orientation\">vertical</property><"
  "child><placeholder/></child><child><object class=\"GtkSearchEntr"
  "y\" id=\"inputtext\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">True</property><property name=\"opac"
  "ity\">0.80000000000000004</property><property name=\"primary_ico"
  "n_name\">edit-find-symbolic</property><property name=\"primary_i"
  "con_activatable\">False</property><property name=\"primary_icon_"
  "sensitive\">False</property><signal handler=\"on_inputtext_key_p"
  "ress_event\" name=\"key-press-event\" swapped=\"no\"/></object><"
  "packing><property name=\"expand\">True</property><property name="
  "\"fill\">False</property><property name=\"position\">1</property"
  "></packing></child><child><placeholder/></child></object><packin"
  "g><property name=\"index\">-1</property></packing></child></obje"
  "ct></child></object></interface>"
};

static const int gladestring_len = 40;